# Generated by Django 3.1.7 on 2021-03-25 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='slider.basemodel')),
                ('slider_name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='sliders/')),
                ('is_publish', models.BooleanField(default=True)),
                ('url_to', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('slider.basemodel',),
        ),
    ]
