# Generated by Django 3.1.7 on 2021-03-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='url_to',
        ),
    ]
